/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9910446e-5ee2-420f-8828-3712b9e9a054",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2FJbJu4Na",
    "aws_user_pools_web_client_id": "68ppikq9rnhvfv6mc7tpjrh6mr",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "MovieDB-dev",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "MovieAPI",
            "endpoint": "https://6l040r6kn1.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
