/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c520134b-be05-4551-998f-a24b4821b9bc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_wgsWHLmtR",
    "aws_user_pools_web_client_id": "29olen64330rfr1overfle1up",
    "oauth": {}
};


export default awsmobile;
